import React, { useEffect, useState } from "react";
import BipInputs from "./bip-inputs/bip-inputs";
import BusInputs from "./bus-inputs/bus-inputs";
import KuposGoInputs from "./kuposgo-inputs/kuposgo-inputs";
import TrainInputs from "./train-inputs/train-inputs";
import TransferInputs from "./transfer-inputs/transfer-inputs";
import { AirportLocations } from "../../../../services/apis/apisAT";

function HomeInputs({
  onKuposGoInputBlur,
  selectedSearchApp,
  t,
  kuposGoObservations,
  kuposGoObservationsError,
  setKuposGoObservations,
  setKuposGoObservationsError,
  setShowAtCounter,
  originType,
  atOriginText,
  setTransferSourceCityError,
  transferSourceCityError,
  setShowOriginTerminalSuggestions,
  setAtOriginText,
  onATInputBlur,
  onTransferChangeFun,
  setPickupTerminal,
  onATInputFocus,
  eraseSelectedInput,
  // atTerminals,
  showOriginTerminalSuggestions,
  airportChoosen,
  renderATTerminals,
  KuposSelectBox,
  select1,
  setKuposGoKuposError,
  select2,
  select3,
  select4,
  setSelect1,
  setSelect2,
  setSelect3,
  setSelect4,
  sourcePlaceholder,
  selectOptions,
  selectSourceCity,
  onSourceChange,
  onInputChange,
  sourceCityError,
  getOriginSelectedFilteredDestinations,
  selectOptions2,
  selectDestinationCity,
  onDestinationChange,
  onInputChange2,
  destinationPlaceholder,
  kuposGoSearchBody,
  serviceList,
  kuposGoData,
  onKuposGoChangeFun,
  onKuposGoTransportInputChange,
  onKuposGoServiceInputChange,
  kuposGoServiceTypeError,
  vehicleList,
  kuposGoVehicleTypeError,
  KuposCounter,
  kuposGoKuposError,
  selectOptionsTrain,
  selectOptions2Train,
  destinationCityError,
  setBipInfoModalShow,
  bipCardNumber,
  onBipDetailsChange,
  onBipDetailsBlur,
  bipCardNumberError,
  bipRutNumber,
  bipRutNumberError,
  bipCardAmount,
  bipCardAmountError,
  bipCardEmail,
  bipCardEmailError,
  bipCardConfirmEmail,
  bipCardConfirmEmailError,
  searchBip,
  selectedBipMethod,
  selectedBipMethodError,
  setKuposGoSourceCityError,
  setThingsOnKuposGoSearchPress,
  destinationType,
  atDestinationText,
  setShowDestinationTerminalSuggestions,
  kuposGoShowReturn,
  onwardDate,
  setAtDestinationText,
  setDestinationTerminal,
  transferDestinationCityError,
  showDestinationTerminalSuggestions,
  transferData,
  transferDateTimeError,
  clearDateTime,
  transferReturnDateTimeError,
  showAtCounter,
  seatTypes,
  searchTransfer,
  onwardDateChange,
  renderKuposGoTabs,
  dateError,
  returnDate,
  returnDateChange,
  kuposGoSelectedTab,
  setKuposGoOriginAddress,
  kuposGoOriginAddress,
  kuposGoSourceCityError,
  kuposGoDateError,
  kuposGoTimeError,
  kuposGoPointsAddressChange,
  viaPointsAddress,
  kuposGoViaError,
  setKuposGoDestinationAddress,
  kuposGoDestinationAddress,
  kuposGoDestinationError,
  showKuposReturnTrip,
  // renderKuposGoReturnInputs,
  kuposGoNameError,
  kuposGoLastNameError,
  kuposGoEmailError,
  kuposGoMobileError,
  kuposGoPostTripDetailsPending,
  kuposGoPostTripDetails,
  dateErrorReturn,
  search,
  searchTrenCentral,
  kuposGoServiceTypeReturnError,
  kuposGoVehicleTypeReturnError,
  kuposGoKuposReturnError,
  setKuposGoOriginAddressReturn,
  kuposGoOriginAddressReturn,
  kuposGoSourceCityReturnError,
  kuposGoDateReturnError,
  kuposGoTimeReturnError,
  viaPointsAddressReturn,
  kuposGoViaReturnError,
  setKuposGoDestinationAddressReturn,
  kuposGoDestinationAddressReturn,
  kuposGoDestinationReturnError,
  setKuposGoShowReturn,
  setKuposGoSelectedTab,
  destinationRef,
}) {
  const getAirportLocations = AirportLocations();

  useEffect(() => {
    getAirportLocations({
      callback: handleAirportLocationsRes,
    });
  }, []);

  const handleAirportLocationsRes = (response) => {
    console.log({ response });
  };

  switch (selectedSearchApp) {
    case 0:
      return (
        <BusInputs
          t={t}
          // transferSourceCityError={transferSourceCityError}
          // setTransferSourceCityError={setTransferSourceCityError}
          selectedSearchApp={selectedSearchApp}
          // setShowAtCounter={setShowAtCounter}
          KuposSelectBox={KuposSelectBox}
          select1={select1}
          setSelect1={setSelect1}
          selectOptions={selectOptions}
          selectSourceCity={selectSourceCity}
          onSourceChange={onSourceChange}
          onInputChange={onInputChange}
          select2={select2}
          setSelect2={setSelect2}
          sourcePlaceholder={sourcePlaceholder}
          sourceCityError={sourceCityError}
          getOriginSelectedFilteredDestinations={
            getOriginSelectedFilteredDestinations
          }
          selectOptions2={selectOptions2}
          selectDestinationCity={selectDestinationCity}
          onDestinationChange={onDestinationChange}
          onInputChange2={onInputChange2}
          destinationPlaceholder={destinationPlaceholder}
          destinationCityError={destinationCityError}
          onwardDate={onwardDate}
          onwardDateChange={onwardDateChange}
          dateError={dateError}
          returnDate={returnDate}
          returnDateChange={returnDateChange}
          dateErrorReturn={dateErrorReturn}
          search={search}
          destinationRef={destinationRef}
        />
      );
    case 1:
      return (
        <TrainInputs
          t={t}
          transferSourceCityError={transferSourceCityError}
          setTransferSourceCityError={setTransferSourceCityError}
          getOriginSelectedFilteredDestinations={
            getOriginSelectedFilteredDestinations
          }
          onInputChange2={onInputChange2}
          selectedSearchApp={selectedSearchApp}
          select1={select1}
          setSelect1={setSelect1}
          selectOptionsTrain={selectOptionsTrain}
          selectSourceCity={selectSourceCity}
          onSourceChange={onSourceChange}
          onInputChange={onInputChange}
          sourcePlaceholder={sourcePlaceholder}
          sourceCityError={sourceCityError}
          select2={select2}
          setSelect2={setSelect2}
          selectOptions2Train={selectOptions2Train}
          onDestinationChange={onDestinationChange}
          selectDestinationCity={selectDestinationCity}
          onwardDate={onwardDate}
          onwardDateChange={onwardDateChange}
          renderKuposGoTabs={renderKuposGoTabs}
          dateError={dateError}
          returnDate={returnDate}
          returnDateChange={returnDateChange}
          searchTrenCentral={searchTrenCentral}
          destinationRef={destinationRef}
        />
      );
    case 2:
      return (
        <TransferInputs
          selectedSearchApp={selectedSearchApp}
          t={t}
          destinationRef={destinationRef}
        />
      );
    case 3:
      return (
        <BipInputs
          t={t}
          transferSourceCityError={transferSourceCityError}
          setTransferSourceCityError={setTransferSourceCityError}
          selectedSearchApp={selectedSearchApp}
          setBipInfoModalShow={setBipInfoModalShow}
          bipCardNumber={bipCardNumber}
          onBipDetailsChange={onBipDetailsChange}
          onBipDetailsBlur={onBipDetailsBlur}
          bipCardNumberError={bipCardNumberError}
          bipCardAmount={bipCardAmount}
          bipCardAmountError={bipCardAmountError}
          bipCardEmail={bipCardEmail}
          bipCardEmailError={bipCardEmailError}
          bipCardConfirmEmail={bipCardConfirmEmail}
          bipCardConfirmEmailError={bipCardConfirmEmailError}
          selectedBipMethod={selectedBipMethod}
          selectedBipMethodError={selectedBipMethodError}
          bipRutNumber={bipRutNumber}
          bipRutNumberError={bipRutNumberError}
          searchBip={searchBip}
        />
      );
    case 4:
      return (
        <KuposGoInputs
          onKuposGoInputBlur={onKuposGoInputBlur}
          select1={select1}
          select2={select2}
          select3={select3}
          select4={select4}
          setSelect1={setSelect1}
          setSelect2={setSelect2}
          setSelect3={setSelect3}
          setSelect4={setSelect4}
          t={t}
          setKuposGoSourceCityError={setKuposGoSourceCityError}
          setKuposGoObservations={setKuposGoObservations}
          setKuposGoObservationsError={setKuposGoObservationsError}
          kuposGoObservations={kuposGoObservations}
          kuposGoObservationsError={kuposGoObservationsError}
          setKuposGoKuposError={setKuposGoKuposError}
          renderKuposGoTabs={renderKuposGoTabs}
          kuposGoServiceTypeReturnError={kuposGoServiceTypeReturnError}
          kuposGoVehicleTypeReturnError={kuposGoVehicleTypeReturnError}
          transferSourceCityError={transferSourceCityError}
          setTransferSourceCityError={setTransferSourceCityError}
          kuposGoSearchBody={kuposGoSearchBody}
          selectedSearchApp={selectedSearchApp}
          KuposSelectBox={KuposSelectBox}
          serviceList={serviceList}
          kuposGoData={kuposGoData}
          onKuposGoChangeFun={onKuposGoChangeFun}
          onKuposGoServiceInputChange={onKuposGoServiceInputChange}
          kuposGoServiceTypeError={kuposGoServiceTypeError}
          vehicleList={vehicleList}
          onKuposGoTransportInputChange={onKuposGoTransportInputChange}
          kuposGoVehicleTypeError={kuposGoVehicleTypeError}
          KuposCounter={KuposCounter}
          kuposGoKuposError={kuposGoKuposError}
          getOriginSelectedFilteredDestinations={
            getOriginSelectedFilteredDestinations
          }
          selectDestinationCity={selectDestinationCity}
          onDestinationChange={onDestinationChange}
          onInputChange2={onInputChange2}
          destinationPlaceholder={destinationPlaceholder}
          destinationCityError={destinationCityError}
          setThingsOnKuposGoSearchPress={setThingsOnKuposGoSearchPress}
          kuposGoShowReturn={kuposGoShowReturn}
          onwardDate={onwardDate}
          kuposGoSelectedTab={kuposGoSelectedTab}
          setKuposGoOriginAddress={setKuposGoOriginAddress}
          kuposGoOriginAddress={kuposGoOriginAddress}
          kuposGoSourceCityError={kuposGoSourceCityError}
          kuposGoDateError={kuposGoDateError}
          kuposGoTimeError={kuposGoTimeError}
          kuposGoPointsAddressChange={kuposGoPointsAddressChange}
          viaPointsAddress={viaPointsAddress}
          kuposGoViaError={kuposGoViaError}
          setKuposGoDestinationAddress={setKuposGoDestinationAddress}
          kuposGoDestinationAddress={kuposGoDestinationAddress}
          kuposGoDestinationError={kuposGoDestinationError}
          showKuposReturnTrip={showKuposReturnTrip}
          kuposGoNameError={kuposGoNameError}
          kuposGoLastNameError={kuposGoLastNameError}
          kuposGoEmailError={kuposGoEmailError}
          kuposGoMobileError={kuposGoMobileError}
          kuposGoPostTripDetailsPending={kuposGoPostTripDetailsPending}
          kuposGoPostTripDetails={kuposGoPostTripDetails}
          kuposGoKuposReturnError={kuposGoKuposReturnError}
          setKuposGoOriginAddressReturn={setKuposGoOriginAddressReturn}
          kuposGoOriginAddressReturn={kuposGoOriginAddressReturn}
          kuposGoSourceCityReturnError={kuposGoSourceCityReturnError}
          kuposGoDateReturnError={kuposGoDateReturnError}
          kuposGoTimeReturnError={kuposGoTimeReturnError}
          viaPointsAddressReturn={viaPointsAddressReturn}
          kuposGoViaReturnError={kuposGoViaReturnError}
          setKuposGoDestinationAddressReturn={
            setKuposGoDestinationAddressReturn
          }
          kuposGoDestinationAddressReturn={kuposGoDestinationAddressReturn}
          kuposGoDestinationReturnError={kuposGoDestinationReturnError}
          setKuposGoShowReturn={setKuposGoShowReturn}
          setKuposGoSelectedTab={setKuposGoSelectedTab}
        />
      );
    default:
      return (
        <BusInputs
          t={t}
          transferSourceCityError={transferSourceCityError}
          setTransferSourceCityError={setTransferSourceCityError}
          selectedSearchApp={selectedSearchApp}
          setShowAtCounter={setShowAtCounter}
          KuposSelectBox={KuposSelectBox}
          select1={select1}
          setSelect1={setSelect1}
          selectOptions={selectOptions}
          selectSourceCity={selectSourceCity}
          onSourceChange={onSourceChange}
          onInputChange={onInputChange}
          select2={select2}
          setSelect2={setSelect2}
          sourcePlaceholder={sourcePlaceholder}
          sourceCityError={sourceCityError}
          getOriginSelectedFilteredDestinations={
            getOriginSelectedFilteredDestinations
          }
          selectOptions2={selectOptions2}
          selectDestinationCity={selectDestinationCity}
          onDestinationChange={onDestinationChange}
          onInputChange2={onInputChange2}
          destinationPlaceholder={destinationPlaceholder}
          destinationCityError={destinationCityError}
          onwardDate={onwardDate}
          onwardDateChange={onwardDateChange}
          dateError={dateError}
          returnDate={returnDate}
          returnDateChange={returnDateChange}
          dateErrorReturn={dateErrorReturn}
          search={search}
        />
      );
  }
}

export default HomeInputs;
