import ContentContainer from "../components/ui/content-container/content-container";
import Head from "next/head";
import MainWrapper from "../components/ui/wrapper/wrapper";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import styles from "../styles/Home.module.less";
import { useRouter } from "next/router";
import { useTranslation } from "next-i18next";
import { Slide } from 'react-slideshow-image';
import 'react-slideshow-image/dist/styles.css'
import { useEffect, useState } from "react";
import EventItem from "../components/home/event-item";
import classes from "./index.module.less"
import { GetEvents } from "../services/apis/apisHome";
import EventsGallery from "../components/Events-gallery";
import EventDescription from "../components/Event_description";

const initSlides = [
  "/images/slides/iust.jpg",
  "/images/slides/iust2.jpg",
  "/images/slides/iust3.jpg",
];

const spanStyle = {
  padding: '20px',
  background: '#efefef',
  color: '#000000'
}

const divStyle = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundSize: 'cover',
  height: '400px'
}



function Home() {
  const router = useRouter();
  const { t } = useTranslation("common");


  const GetEventsFunc = GetEvents();

  const [events, setEvents] = useState([
    { id: 0, title: "Event 1 in IUST Science Block", body: "For using the full-screen navigation HOCs please checkout the GatsbyJS and NextJS examples on the ras fullpage strategies repository. You can access the demo for the FULLPAGE navigation here: fullpage.caferati.me", date: "30/06/2023" },
    { id: 0, title: "Event 1 in IUST Science Block", body: "For using the full-screen navigation HOCs please checkout the GatsbyJS and NextJS examples on the ras fullpage strategies repository. You can access the demo for the FULLPAGE navigation here: fullpage.caferati.me", date: "30/06/2023" },
    { id: 0, title: "Event 1 in IUST Science Block", body: "For using the full-screen navigation HOCs please checkout the GatsbyJS and NextJS examples on the ras fullpage strategies repository. You can access the demo for the FULLPAGE navigation here: fullpage.caferati.me", date: "30/06/2023" },
  ])
  // const newEvents= events.filter(function)


  useEffect(() => {

    GetEventsFunc({
      callback: res => {
        console.log("respo from api---", Object.values(res))

        if (res) {
          setEvents(Object.values(res).slice(0, 99))
        }
      }
    })


  }, [])

  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>cumputer-club</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>




        <Slide>
          {initSlides.map((slideImage, index) => (
            <div key={index}>
              <div style={{ ...divStyle, 'backgroundImage': `url(${slideImage})` }}>
                <span style={spanStyle}>{slideImage.caption}</span>
              </div>
            </div>
          ))}
        </Slide>





        <ContentContainer>
          <div className={classes.events_heading}>News & Events</div>

          <div>
            <div className={classes.gallery_section}>
              <div className={classes.gallery_heading}>PHOTO GALLERY</div>
            <div className={classes.events_gallery}>
              <EventsGallery />
              </div>
              <div className={classes.viewall_button}>View All</div>
              </div>
            <div>
              <div className={classes.events_created}>Events,Workshops And Seminars</div>
              <div className={classes.type_events}>
                <span className={classes.held_button}>Events Held</span>
                <span className={classes.upcomming_button}>Upcoming Events</span>
              </div>
              <div className={classes.events_container}>

                {events?.map((event, index) => {
                  return <EventItem event={event} index={index} />
                })}
              </div>
            </div>
          </div>
          <div>
          {/* <EventDescription  /> */}
          </div>

        </ContentContainer>
      </div>
    </MainWrapper>
  );
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "es", ["common"])),
  },
});

export default Home;
